# Generated by Django 3.1.4 on 2020-12-20 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('max_marcianos', models.IntegerField(default=4, verbose_name='aforo maximo nave')),
            ],
        ),
        migrations.CreateModel(
            name='Marciano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='NaveNodriza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_revisor', models.CharField(max_length=32, verbose_name='nombre del revisor')),
                ('fecha_revision', models.DateTimeField(verbose_name='fecha de revision')),
                ('aeronave_revisada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigemapp.aeronave')),
                ('pasajeros', models.ManyToManyField(to='sigemapp.Marciano')),
            ],
        ),
        migrations.CreateModel(
            name='AsignarPasajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigemapp.aeronave')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigemapp.marciano')),
            ],
        ),
        migrations.AddField(
            model_name='aeronave',
            name='nave_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nave_destino', to='sigemapp.navenodriza'),
        ),
        migrations.AddField(
            model_name='aeronave',
            name='nave_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nave_origen', to='sigemapp.navenodriza'),
        ),
    ]
