# Generated by Django 3.1.4 on 2020-12-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigemapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='fecha_revision',
            field=models.DateField(verbose_name='fecha de revision'),
        ),
    ]
