# Generated by Django 3.1.4 on 2020-12-20 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigemapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeleccionarPasajeroBajarO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altaPasajero', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sigemapp.asignarpasajero')),
            ],
        ),
    ]
