# Generated by Django 3.1.4 on 2020-12-13 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sigemapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeronave',
            name='pasajeros',
        ),
        migrations.AddField(
            model_name='revision',
            name='fecha_revision',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 19, 7, 15, 510553, tzinfo=utc), verbose_name='fecha de revision'),
        ),
        migrations.AddField(
            model_name='revision',
            name='pasajeros',
            field=models.ManyToManyField(to='sigemapp.Marciano'),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='max_marcianos',
            field=models.IntegerField(default=4, verbose_name='aforo maximo nave'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='nombre_revisor',
            field=models.CharField(max_length=32, verbose_name='nombre del revisor'),
        ),
    ]
